config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check
  resources :users, only: [:update]
  resources :parties, only: %i[index show new create] do
    member do
      get :start
      put :start
      get :result
      get :final_result
      get :check_completion
    end
    resources :swipes, only: %i[index new create] do
      collection do
        post :undo
        post :final
      end
    end
  end
end

app/models/party.rb
require "open-uri"
require "json"

class Party < ApplicationRecord
  belongs_to :admin, class_name: 'User', foreign_key: 'user_id'
  has_many :party_players, dependent: :destroy
  has_many :users, through: :party_players
  has_many :swipes, through: :party_players

  after_update :assign_movies!, if: :saved_change_to_start?

  PROVIDERS = [
    { name: "Netflix", id: "8" },
    { name: "Prime", id: "119" },
    { name: "AppleTV+", id: "350" },
    { name: "Disney+", id: "337" }
  ]

  GENRES = [
    { name: "Action", id: 28 },
    { name: "Adventure", id: 12 },
    { name: "Animation", id: 16 },
    { name: "Comedy", id: 35 },
    { name: "Crime", id: 80 },
    { name: "Documentary", id: 99 },
    { name: "Drama", id: 18 },
    { name: "Family", id: 10751 },
    { name: "Fantasy", id: 14 },
    { name: "History", id: 36 },
    { name: "Horror", id: 27 },
    { name: "Music", id: 10402 },
    { name: "Mystery", id: 9648 },
    { name: "Romance", id: 10749 },
    { name: "Science Fiction", id: 878 },
    { name: "TV Movie", id: 10770 },
    { name: "Thriller", id: 53 },
    { name: "War", id: 10752 },
    { name: "Western", id: 37 }
  ]

  validate :at_least_one_platform_selected

  def platform_setting=(values)
    super(Array(values))
  end

  def category_setting=(values)
    super(Array(values))
  end

  def fetch_movie_providers(movie_id)
    begin
      url = "https://api.themoviedb.org/3/movie/#{movie_id}/watch/providers?api_key=#{ENV['TMDB_API_KEY']}&watch_region=FR"
      response = URI.open(url).read
      parsed_response = JSON.parse(response)

      # Get French providers from the flatrate category
      providers = parsed_response.dig("results", "FR", "flatrate")
      return [] unless providers

      providers.map { |provider| provider["provider_id"].to_s }
    rescue OpenURI::HTTPError, JSON::ParserError => e
      Rails.logger.error "Error fetching providers for movie #{movie_id}: #{e.message}"
      return []
    end
  end

  def assign_movies!
    all_movies = []

    for i in 1..20
      url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-EN&watch_region=FR&page=#{i}"
      url += "&with_watch_providers=#{platform_setting.join('|')}" if platform_setting.present?
      url += "&with_genres=#{category_setting.join('|')}" if category_setting.present?
      url += "&primary_release_date.gte=#{start_year}-01-01" if start_year.present?
      url += "&primary_release_date.lte=#{end_year}-12-31" if end_year.present?
      url += "&api_key=#{ENV['TMDB_API_KEY']}"

      response = URI.open(url).read
      parsed_response = JSON.parse(response)
      all_movies.concat(parsed_response["results"])
    end

    party_players.each do |party_player|
      selected_movies = all_movies.sample(10)

      # Add provider information to each movie
      selected_movies.each do |movie|
        movie["available_providers"] = fetch_movie_providers(movie["id"])
      end

      party_player.update(movies: selected_movies)
    end

    all_player_movies = party_players.map { |player| player.movies }.flatten.map { |movie| movie["id"] }
    update(movies: all_player_movies)
  end

  def started?
    start
  end

  def movies_assigned?
    movies.present?
  end

  def all_players_finished_swiping?
    party_players.all? do |player|
      player.swipes.count >= player.movies.count
    end
  end

  def assign_final_movies!
    # Return existing final_movies if they are already set and not empty
    return final_movies if final_movies.present?
    return [] unless all_players_finished_swiping?

    # Get all liked swipes and their tags
    tags_liked = swipes.where(is_liked: true).pluck(:tags).flatten
    return [] if tags_liked.empty?

    # Update party tags and get most common ones
    update(tags: tags_liked)
    tags_count = tags_liked.tally
    max_count = tags_count.values.max
    tags_final = tags_count.select { |_key, value| value == max_count }.keys

    all_movies = []

    for i in 1..5
      url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&watch_region=FR&page=#{i}"
      url += "&with_watch_providers=#{platform_setting.join('|')}" if platform_setting.present?
      url += "&with_genres=#{tags_final.join('|')}" if tags_final.present?
      url += "&primary_release_date.gte=#{start_year}-01-01" if start_year.present?
      url += "&primary_release_date.lte=#{end_year}-12-31" if end_year.present?
      url += "&api_key=#{ENV['TMDB_API_KEY']}"

      response = URI.open(url).read
      parsed_response = JSON.parse(response)
      all_movies.concat(parsed_response["results"])
    end

    # Filter out movies that were already shown and select 3 random ones
    final_movies = (all_movies.reject { |movie| movies.include?(movie["id"]) }).sample(3)

    # Add provider information to final movies
    final_movies.each do |movie|
      movie["available_providers"] = fetch_movie_providers(movie["id"])
    end

    if final_movies.present?
      update(final_movies: final_movies)
    end

    final_movies
  end

  def all_players_finished_final_swipes?
    party_players.all? do |player|
      player.swipes.where(movie_id: final_movies.map { |m| m['id'] }).count >= final_movies.length
    end
  end

  private

  def at_least_one_platform_selected
    if platform_setting.blank?
      errors.add(:platform_setting, "must include at least one platform provider")
    end
  end
end

app/controllers/parties_controller.rb
require "open-uri"
require "json"


class PartiesController < ApplicationController
  before_action :fetch_categories, only: :new

  def index
    if params[:party_code].present?
      party = Party.find_by(party_code: params[:party_code])
      if party
        if !party.start?
          @party_player = PartyPlayer.create(user: current_or_guest_user, party: party)
          Turbo::StreamsChannel.broadcast_update_to(
            "party_#{party.id}",
            target: "players_list",
            partial: "parties/players_list",
            locals: { party: party }
          )
          Turbo::StreamsChannel.broadcast_update_to(
            "party_#{party.id}",
            target: "players_count",
            partial: "parties/players_count",
            locals: { party: party }
          )
          redirect_to party_path(party)
        else
          flash.now[:alert] = "Party already started"
          render :index
        end
      else
        flash.now[:alert] = "Invalid code"
        render :index
      end
    end
  end

  def show
    @party = Party.find(params[:id])
    @party_player = @party.party_players.find_by(user: current_or_guest_user)
  end

  def new
    @party = Party.new
  end

  def start
    @party = Party.find(params[:id])
    if @party.update(start: true)
      ActionCable.server.broadcast(
        "party_#{@party.id}",
        {
          action: "game_started",
          redirect_url: party_swipes_path(@party)
        }
      )
      redirect_to party_swipes_path(@party)
    else
      render :show, status: :unprocessable_entity
    end
  end

  def create
    @party = Party.new(party_params)
    @party.start = false
    @party.admin = current_or_guest_user
    @party.party_code = rand(100000..999999)

    current_or_guest_user.update(
      username: params[:username],
      avatar: params[:avatar]
    )

    if @party.save
      PartyPlayer.create(user: current_or_guest_user, party: @party)
      redirect_to party_path(@party), notice: 'Party was successfully created.'
    else
      redirect_to new_party_path
      flash[:alert] = "You must select at least one platform provider to start the party."
    end
  end

  def result
    @party = Party.find(params[:id])
    @party_player = @party.party_players.find_by(user: current_or_guest_user)

    if @party.final_movies.empty? && @party.all_players_finished_swiping?
      assigned_movies = @party.assign_final_movies!
      @party.update!(final_movies: assigned_movies)
    end

    @final_movies = @party.final_movies
  end

  def final_result
    @party = Party.find(params[:id])
    @party_player = PartyPlayer.find_by(user: current_or_guest_user, party: @party)

    # Get all liked swipes for the final movies
    @movies_liked = @party.swipes
      .where(is_liked: true)
      .where(movie_id: @party.final_movies.map { |m| m['id'] })
      .group(:movie_id)
      .count

    total_players = @party.party_players.count

    # Determine the winning movie
    unanimous_movies = @movies_liked.select { |_movie_id, likes| likes == total_players }.keys
    @winning_movie =
      if unanimous_movies.any?
        unanimous_movies.first
      else
        @movies_liked.max_by { |_movie_id, count| count }&.first
      end

    # Make API call to get movie videos if we have a winning movie
    if @winning_movie
      api_key = ENV["TMDB_API_KEY"]
      url = "https://api.themoviedb.org/3/movie/#{@winning_movie}/videos?language=en-US&api_key=#{api_key}"
      response = URI.open(url).read
      videos_data = JSON.parse(response)

      # Find the first trailer or fallback to first video
      @video = videos_data["results"].find { |v| v["type"] == "Trailer" } || videos_data["results"].first
    end
  end

  def check_completion
    @party = Party.find(params[:id])
    all_completed = @party.party_players.all?(&:done?)

    if all_completed
      ActionCable.server.broadcast(
        "party_#{@party.id}",
        {
          action: 'all_completed'
        }
      )
    end

    render json: { all_completed: all_completed }
  end

  private

  def party_params
    params.require(:party).permit(:start_year, :end_year, category_setting: [], platform_setting: [])
  end

  def fetch_categories
    api_key = ENV["TMDB_API_KEY"]
    url = "https://api.themoviedb.org/3/genre/movie/list?language=en-US&api_key=#{api_key}"
    response = URI.open(url).read
    @categories = JSON.parse(response)["genres"]
  end

  def find_winning_movie

  end
end

app/views/parties/_final_movies.html.erb
<div data-controller="swiper" data-swiper-results="true" data-action="swiper:tinderSwipe@document->swiper#handleSwipe" data-swiper-party-id-value="<%= @party.id %>" data-swiper-party-player-id-value="<%= PartyPlayer.find_by(user: current_or_guest_user, party: @party).id %>" class="swiper swiper-tinder swiper-3d swiper-initialized swiper-horizontal swiper-watch-progress">
  <div class="swiper-wrapper" style="cursor: grab;">
    <% final_movies.each do |final_movie| %>
      <div data-movie-id="<%= final_movie["id"] %>" class="swiper-slide swiper-slide-visible swiper-slide-fully-visible swiper-slide-active" style="width: 100%; transform: translate3d(0px, 0px, 0px) rotateZ(0deg); opacity: 1;">
        <%= image_tag "https://image.tmdb.org/t/p/w500#{final_movie["poster_path"]}", style: "width: 100%;" %>
        <div class="swiper-tinder-label swiper-tinder-label-yes" style="opacity: 0;">Like</div>
        <div class="swiper-tinder-label swiper-tinder-label-no" style="opacity: 0;">Nope</div>
      </div>
    <% end %>
  <button class="swiper-tinder-button swiper-tinder-button-no">
    <svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="48">
      <path d="m249-207-42-42 231-231-231-231 42-42 231 231 231-231 42 42-231 231 231 231-42 42-231-231-231 231Z"></path>
    </svg>
  </button>
  <button class="swiper-tinder-button swiper-tinder-button-yes">
    <svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="48">
      <path d="m480-121-41-37q-106-97-175-167.5t-110-126Q113-507 96.5-552T80-643q0-90 60.5-150.5T290-854q57 0 105.5 27t84.5 78q42-54 89-79.5T670-854q89 0 149.5 60.5T880-643q0 46-16.5 91T806-451.5q-41 55.5-110 126T521-158l-41 37Z"></path>
    </svg>
  </button>
</div>

app/views/parties/_players_count.html.erb
<div class="count-players text-center">
  <h3>
    <% if party.party_players.count == 1 %>
      <%= party.party_players.count %> PLAYER
    <% else %>
      <%= party.party_players.count %> PLAYERS
    <% end %>
  </h3>
</div>

app/views/parties/_players_list.html.erb
<div class="players-list mt-3">
  <div class="d-flex flex-wrap gap-4 justify-content-center">
    <% party.party_players.each do |player| %>
      <div class="player-item text-center">
        <%= image_tag "avatars/#{player.user.avatar}",
            class: "avatar-img",
            style: "width: 70px; height: 70px; border-radius: 50%; object-fit: cover;" %>
        <div class="username mb-0"><%= player.user.username %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/parties/final_result.html.erb
<% content_for :meta_title, "ReelMates - Your Final Movie" %>
<% content_for :meta_description, "Congratulations! You've found the perfect movie for your movie night. Sit back, relax, and enjoy the show with your friends!" %>

<div class="container-fluid d-flex justify-content-center" style="min-height: 100vh; color: white;">
  <div class="row w-100">
    <div class="col-12 col-md-8 offset-md-2 ps-4 pe-4">
      <% winning_movie_data = @party.final_movies.find { |m| m['id'] == @winning_movie } %>
      <% if @movies_liked[@winning_movie] == @party.party_players.count %>
        <div class="text-center mt-5" data-controller="match-animation">
          <h2 style="font-size: 32px; color: #F66426; font-weight: bold; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); letter-spacing: 1px; margin-bottom: 20px;">
            IT'S A MATCH! 🎉
          </h2>
        </div>
      <% else %>
        <div class="text-center mt-5">
          <h2 style="font-size: 36px; color: #F66426; font-weight: bold; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); letter-spacing: 1px; margin-bottom: 20px;">MOST LIKED MOVIE</h2>
          <p><%= @movies_liked[@winning_movie] %> out of <%= @party.party_players.count %> players liked this movie</p>
        </div>
      <% end %>
      <% if winning_movie_data %>
        <div class="d-flex justify-content-center align-items-center">
          <div class="flip-card movie-result text-center mt-3 mb-4"
               data-controller="flip-card"
               style="box-shadow: 0 4px 8px rgba(255, 255, 255, 0.1);">
            <div class="flip-card-inner">
              <div class="flip-card-front">
                <%= image_tag "https://image.tmdb.org/t/p/w500#{winning_movie_data['poster_path']}",
                    class: "movie-poster",
                    style: "width: 100%; height: 100%; object-fit: cover; border-radius: 8px;" %>
              </div>

              <div class="flip-card-back text-center position-relative"
                   style="background: linear-gradient(rgba(0, 0, 0, 0.75), rgba(0, 0, 0, 0.75)),
                          url('https://image.tmdb.org/t/p/w500<%= winning_movie_data['poster_path'] %>');
                   background-size: cover;
                   background-position: center;
                   backdrop-filter: blur(8px);
                   -webkit-backdrop-filter: blur(8px);
                   padding: 20px 32px;
                   border-radius: 8px;
                   box-shadow: 0 4px 8px rgba(255, 255, 255, 0.1);">

                <h3 class="mt-2" style="font-weight: bold; color: #FFFFFF; max-height: 3em; overflow: hidden; text-overflow: ellipsis; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; white-space: normal;">
                  <%= winning_movie_data['title'] %>
                </h3>

                <div class="text-center mt-1" style="max-width: 100%; overflow: hidden;">
                  <p class="text-white opacity-75 mb-1" style="font-size: 0.9em; display: inline;"><%= winning_movie_data['release_date'].to_date.strftime("%Y") %></p>
                  <i class="fa-solid fa-circle" style="font-size: 0.3em; vertical-align: middle; margin: 0 0.5em; opacity: 0.75;"></i>
                  <p class="text-white opacity-75 mb-2" style="font-size: 0.9em; display: inline; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 70%;"><%= winning_movie_data['genre_ids'].map { |id| Party::GENRES.find { |g| g[:id] == id }[:name] }.join(", ") %></p>
                </div>

                <div class="position-absolute mt-2" style="top: 50%; left: 50%; transform: translate(-50%, -50%); width: 90%;">
                  <p class="my-1 pb-2" style="font-size: 1.0em; color: rgba(255, 255, 255, 0.75); font-weight: bold;">Synopsis</p>
                  <p class="movie-overview px-2 mt-0 pb-3" style="font-size: 0.9em; line-height: 1.5; max-height: 200px; overflow-y: auto; text-align: justify;">
                    <%= winning_movie_data['overview'] %>
                  </p>
                </div>

                <div class="d-flex justify-content-center align-items-center position-absolute" style="bottom: 60px; left: 0; right: 0;">
                  <p class="text-white opacity-75 mb-2" style="font-size: 1.1em;">
                    Available on
                    <% if winning_movie_data["available_providers"].present? %>
                      <% Party::PROVIDERS
                          .select { |p| winning_movie_data["available_providers"].include?(p[:id]) }
                          .each do |provider| %>
                        <span class="provider-name" style="color: #F66426; font-weight: bold; margin-left: 4px;">
                          <%= provider[:name] %><%= " • " unless provider == Party::PROVIDERS.select { |p| winning_movie_data["available_providers"].include?(p[:id]) }.last %>
                        </span>
                      <% end %>
                    <% else %>
                      <span style="color: #999; margin-left: 4px;">Not available on selected platforms</span>
                    <% end %>
                  </p>
                </div>

                <div>
                  <p class="position-absolute badge text-light" style="bottom: 4px; right: 16px; font-size: 0.9em; padding: 0.5em 1em; border-radius: 4px; background-color: #F66426;">
                  <i class="fa-solid fa-thumbs-up"></i>
                   <%= (winning_movie_data['vote_average'] * 10).to_i %>%
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

     <% if @video %>
        <div class="accordion-container mt-3">
          <div class="accordion" id="yourAccordionId">
            <div class="accordion-item" style="border-radius: 16px;">
              <h2 class="accordion-header">
                <button class="accordion-button collapsed" style="border-radius: 16px;" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne"
                        style="transition: all 0.3s ease; opacity: 0.9;"
                        onmouseover="this.style.opacity='1'; this.style.transform='scale(1.02)'"
                        onmouseout="this.style.opacity='0.9'; this.style.transform='scale(1)'">
                  Watch Trailer
                </button>
              </h2>
              <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#yourAccordionId">
                <div class="accordion-body">
                  <div class="ratio ratio-16x9 mb-4">
                    <iframe
                      src="https://www.youtube.com/embed/<%= @video['key'] %>"
                      title="<%= @video['name'] %>"
                      frameborder="0"
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                      allowfullscreen>
                    </iframe>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>
<style>
.accordion-button:not(.collapsed)::after {
  background-color: transparent;
}
</style>

app/views/parties/index.html.erb
<% content_for :meta_title, "ReelMates - Start or Join Your Movie Party" %>
<% content_for :meta_description, "Create or join a movie party on ReelMates and get ready to discover the perfect movie for your group. Fun, fast, and easy movie selection for friends and couples." %>

<div class="container-fluid d-flex justify-content-center align-items-center" style="min-height: 100vh; color: white;">
  <div class="row w-100">
    <div class="col-12 col-md-8 offset-md-2 ps-4 pe-4">
      <div class="player-item d-flex align-items-center justify-content-center mb-3 gap-2">
        <h2 class="mb-0" style="font-weight: 700; font-size: 2rem;">Hi <%= current_or_guest_user.username %></h2>
        <%= image_tag "avatars/#{current_or_guest_user.avatar}",
            class: "avatar-img",
            style: "width: 60px; height: 60px; border-radius: 50%; object-fit: cover;" %>
    </div>
      <div class="text-center mb-4">
        <%# <h4 class="mb-2">Welcome</h4> %>
        <p class="mb-3">Please follow our House Rules:</p>
      </div>
      <div class="d-flex align-items-center mb-2">
        <i class="fa-solid fa-check fa-lg me-2" style="color: #f66426;"></i>
        <h5 class="m-0">Be Honest.</h5>
      </div>
      <p class="mb-4 ms-4">Swipe only on movies you're genuinely interested in watching.</p>
      <div class="d-flex align-items-center mb-2">
        <i class="fa-solid fa-check fa-lg me-2" style="color: #f66426;"></i>
        <h5 class="m-0">Respect Time.</h5>
      </div>
      <p class="mb-4 ms-4">Complete swiping rounds promptly to keep the game moving.</p>
      <div class="d-flex align-items-center mb-2">
        <i class="fa-solid fa-check fa-lg me-2" style="color: #f66426;"></i>
        <h5 class="m-0">Stay Open-Minded.</h5>
      </div>
      <p class="mb-4 ms-4">Consider new genres or movies you haven't watched before.</p>
      <div class="d-flex align-items-center mb-2">
        <i class="fa-solid fa-check fa-lg me-2" style="color: #f66426;"></i>
        <h5 class="m-0">Collaborate.</h5>
      </div>
      <p class="mb-4 ms-4">Discuss the final result respectfully if opinions differ.</p>
      <div class="text-center mt-2">
        <%= link_to "CREATE A PARTY", new_party_path, class: "btn button-orange shadow w-100 m-0 fw-bold mb-2" %>
        <div class="or-divider">
          <span class="line"></span>
          <span class="or-text">OR</span>
          <span class="line"></span>
        </div>
        <%= form_with url: parties_path, method: :get do |f| %>
          <%= f.text_field :party_code,
                          placeholder: "Enter party code",
                          class: "form-control rounded-pill mb-4"%>
          <%= f.submit "JOIN A PARTY", class: "btn button-orange shadow w-100 m-0 fw-bold" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/parties/new.html.erb
<% content_for :meta_title, "ReelMates - Set Up Your Movie Party" %>
<% content_for :meta_description, "Customize your movie party settings. Choose your platform, movie categories, and preferences to get personalized movie recommendations with friends." %>

<div class="container">
  <div class="row">
    <div data-controller="checkbox" class="container-fluid d-flex justify-content-center align-items-center" style="min-height: 100vh; color: white;">
      <div class="row w-100">
        <div class="settings col-12 col-md-8 offset-md-2">
          <div class="text-center mb-4 mt-2">
            <h2 class="mb-2" style="font-weight: 700; font-size: 2rem;">Party Settings</h2>
          </div>
          <div class="text-left">
            <h4 class="title-settings mb-3">Platforms</h4>
            <p class="text-muted">Please select at least one platform.</p>
          </div>

          <%= simple_form_for @party do |f| %>
            <% if @party.errors.any? %>
              <div class="alert alert-danger text-center">
                <h2><%= pluralize(@party.errors.count, "error") %> prohibited this party from being saved:</h2>
                <ul>
                  <% @party.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="d-flex flex-wrap mb-3">
              <% Party::PROVIDERS.each do |provider| %>
                <div class="custom-checkbox-wrapper">
                  <%= check_box_tag 'party[platform_setting][]', provider[:id], false, id: "platform_#{provider[:id]}", class: 'd-none', onclick: 'toggleCheckboxState(this)' %>
                  <label for="platform_<%= provider[:id] %>" class="custom-checkbox">
                    <span class="checkbox-label"><%= provider[:name] %></span>
                    <i class="fa fa-check" aria-hidden="true"></i>
                  </label>
                </div>
              <% end %>
            </div>

            <div class="text-left mt-3">
              <h4 class="title-settings mb-3">Periods</h4>
            </div>

            <div class="d-flex flex-column align-items-center mb-2">
              <label for="year-slider">Select Year Range:</label>
              <div id="year-slider" style="margin: 20px 0;"></div>
              <div class="d-none" style="display: flex; justify-content: space-between; margin-top: 10px;">
                <span id="start-year-display">1920</span>
                <span id="end-year-display">2024</span>
              </div>

              <%= f.hidden_field :start_year, id: "start_year_input" %>
              <%= f.hidden_field :end_year, id: "end_year_input" %>

            </div>

            <div class="text-left">
              <h4 class="title-settings mb-3 mt-2">Categories</h4>
            </div>

            <div class="d-flex flex-wrap">
              <% Party::GENRES.each do |genre| %>
                <div class="custom-checkbox-wrapper">
                  <%= check_box_tag 'party[category_setting][]', genre[:id], false, id: "category_#{genre[:id]}", class: 'd-none', onclick: 'toggleCheckboxState(this)' %>
                  <label for="category_<%= genre[:id] %>" class="custom-checkbox">
                    <span class="checkbox-label"><%= genre[:name] %></span>
                    <i class="fa-solid fa-check fa-sm" style="color: #ffffff;" aria-hidden="true"></i>
                  </label>
                </div>
              <% end %>
            </div>

            <div class="d-flex justify-content-center flex-column align-items-center">
              <%= f.submit "CREATE", class: "btn button-orange shadow w-100 m-0 fw-bold mt-4 mb-3" %>
              <%= link_to "BACK", parties_path, class: "text-center text-black text-decoration-none w-100 m-0 fw-bold" %>
            </div>
          <% end %>

          <script>
            document.addEventListener("turbo:load", () => {
              const slider = document.getElementById("year-slider");
              const startYearDisplay = document.getElementById("start-year-display");
              const endYearDisplay = document.getElementById("end-year-display");
              const startYearInput = document.getElementById("start_year_input");
              const endYearInput = document.getElementById("end_year_input");

              if (slider) {
                noUiSlider.create(slider, {
                  start: [1920, 2024],
                  connect: true,
                  range: {
                    min: 1920,
                    max: 2024
                  },
                  step: 10,  // Updated step value to 10
                  tooltips: [true, true],
                  format: {
                    to: value => Math.round(value),
                    from: value => Math.round(value)
                  }
                });

                slider.noUiSlider.on("update", (values) => {
                  const [start, end] = values.map(value => Math.round(value));
                  startYearDisplay.textContent = start;
                  endYearDisplay.textContent = end;

                  startYearInput.value = start;
                  endYearInput.value = end;
                });
              }
            });
          </script>

          <script>
            function toggleCheckboxState(checkbox) {
              const label = checkbox.nextElementSibling;
              const checkIcon = label.querySelector('.fa-check');
              const textLabel = label.querySelector('.checkbox-label');

              if (checkbox.checked) {
                checkIcon.style.display = 'inline-block';
                textLabel.classList.add('reduced-text');
              } else {
                checkIcon.style.display = 'none';
                textLabel.classList.remove('reduced-text');
              }
            }
          </script>
        </div>
      </div>
    </div>
  </div>
</div>